-- Generate tools/wow/forever_api.lua from Ketho/BlizzardInterfaceResources files.
-- Usage: lua tools/wow/gen.lua <resources dir> <commit> <build> > tools/wow/forever_api.lua
-- Runs under PUC Lua 5.1, which is also how it decides which of WoW's Lua
-- functions exist in plain Lua 5.1 too (the "portable" set pure Core code may use).

local dir, commit, build = ...
assert(dir and commit and build, "usage: gen.lua <resources dir> <commit> <build>")

-- Resource files are Lua: most return a table, LuaEnum.lua assigns globals instead.
local function load(name)
  local chunk = assert(loadfile(dir .. "/" .. name .. ".lua"))
  local env = {}
  setfenv(chunk, env)
  return chunk(), env
end

local function sorted(list)
  local seen, out = {}, {}
  for _, v in ipairs(list) do
    if not seen[v] then
      seen[v] = true
      out[#out + 1] = v
    end
  end
  table.sort(out)
  return out
end

-- Resolve a dotted name like "string.format" against this interpreter's globals.
local function inPlainLua(name)
  local value = _G
  for part in name:gmatch("[^.]+") do
    if type(value) ~= "table" then
      return false
    end
    value = value[part]
  end
  return value ~= nil
end

local apiLists = load("GlobalAPI")
local globalApi, luaApi = apiLists[1], apiLists[2]
-- FrameXML and Frames return { always loaded, load-on-demand }. Load-on-demand names
-- exist only after their Blizzard_* addon loads, so they are kept apart.
local frameXmlLists = load("FrameXML")
local frameLists = load("Frames")
local _, enumEnv = load("LuaEnum")
local eventsBySystem = load("Events")
local widgets = load("WidgetAPI")

local portable = {}
for _, name in ipairs(luaApi) do
  if inPlainLua(name) then
    portable[#portable + 1] = name
  end
end

local events = {}
for _, list in pairs(eventsBySystem) do
  for _, event in ipairs(list) do
    events[#events + 1] = event
  end
end

local globalTables = {}
for name in pairs(enumEnv) do
  globalTables[#globalTables + 1] = name
end

local out = {}
local function emit(line)
  out[#out + 1] = line
end
local function emitList(key, list, comment)
  emit("  -- " .. comment)
  emit("  " .. key .. " = {")
  for _, v in ipairs(sorted(list)) do
    emit(string.format("    %q,", v))
  end
  emit("  },")
end

emit("-- GENERATED by `make wow-api` from Ketho/BlizzardInterfaceResources, forever branch.")
emit("-- Do not edit. Regenerate after bumping WOW_RESOURCES_COMMIT in tools/versions.")
emit("return {")
emit(string.format("  build = %q,", build))
emit(string.format("  commit = %q,", commit))
emitList("lua", luaApi, "WoW's Lua API: builtins plus WoW's extensions (strsplit, wipe, table.wipe...).")
emitList("portable", portable, "The part of `lua` that plain Lua 5.1 also has. Pure Core code may use only these.")
emitList("api", globalApi, "Global API functions, including C_* namespaces as dotted names.")
emitList("framexml", frameXmlLists[1], "Functions Blizzard's always-loaded UI code defines.")
emitList("framexml_lod", frameXmlLists[2], "Functions that exist only once their load-on-demand Blizzard addon loads.")
emitList("frames", frameLists[1], "Named frames Blizzard's always-loaded UI creates.")
emitList("frames_lod", frameLists[2], "Named frames that exist only once their load-on-demand addon loads.")
emitList("tables", globalTables, "Globals LuaEnum defines: Enum, Constants and the LE_* / NUM_LE_* constants.")
emitList("events", events, "Every event the client knows. Registering any other name throws.")
emit("  -- Widget types: which methods each has and which types it inherits from.")
emit("  widgets = {")
local widgetNames = {}
for name in pairs(widgets) do
  widgetNames[#widgetNames + 1] = name
end
table.sort(widgetNames)
for _, name in ipairs(widgetNames) do
  local widget = widgets[name]
  emit(string.format("    [%q] = {", name))
  local inherits = {}
  for _, parent in ipairs(widget.inherits or {}) do
    inherits[#inherits + 1] = string.format("%q", parent)
  end
  emit("      inherits = { " .. table.concat(inherits, ", ") .. " },")
  emit("      methods = {")
  for _, method in ipairs(sorted(widget.methods or {})) do
    emit(string.format("        %q,", method))
  end
  emit("      },")
  emit("    },")
end
emit("  },")
emit("}")

io.write(table.concat(out, "\n"), "\n")
